/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ShiftRegDriver */

#ifndef _Included_ShiftRegDriver
#define _Included_ShiftRegDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ShiftRegDriver
 * Method:    shiftOut
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_ShiftRegDriver_shiftOut
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
